googlemaps/google-maps-ios-utils

- Google-Maps-iOS-Utils.podspec
Fix for https://github.com/googlemaps/google-maps-ios-utils/issues/19
> Work around cocoapods issue with GoogleMaps 2.0.0

- app/AppApiKey.h
- app/BasicViewController.h
- app/BasicViewController.m
- app/CustomMarkerViewController.h
- app/CustomMarkerViewController.m
- app/MasterViewController.h
- app/MasterViewController.m
- app/Samples.h
- app/Samples.m
- src/Clustering/View/GMUDefaultClusterRenderer.h
- src/Clustering/View/GMUDefaultClusterRenderer.m
- workspace/GoogleMapsUtils.xcodeproj/project.pbxproj
- workspace/XcodeConfig/GMU-DevApp.debug.xcconfig
- workspace/XcodeConfig/GMU-DevApp.release.xcconfig
- workspace/XcodeConfig/GMU-UnitTest.debug.xcconfig
- workspace/XcodeConfig/GMU-UnitTest.release.xcconfig
Addressing:
- https://github.com/googlemaps/google-maps-ios-utils/issues/44
- https://github.com/googlemaps/google-maps-ios-utils/issues/42
- https://github.com/googlemaps/google-maps-ios-utils/issues/34
> Allowed easy customization of markers

- Google-Maps-iOS-Utils.podspec
@mountainvat I think this works, but I haven't figured out how to use the GeoJSON parser from Swift successfully. Currently I'm failing to convince Xcode to import the headers...
> Adding Geometry

- CONTRIBUTORS.txt
- src/Clustering/View/GMUDefaultClusterIconGenerator.h
- src/Clustering/View/GMUDefaultClusterIconGenerator.m
Couldn't figure out how to set my own background colors on clusters in the icon generator without modifying the code so made a new constructor for that purpose.
> Add constructor for setting custom background colors of clusters

- CONTRIBUTORS.txt
- app/HeatmapViewController.h
- app/HeatmapViewController.m
- app/Samples.m
- src/Heatmap/GMUGradient.h
- src/Heatmap/GMUGradient.m
- src/Heatmap/GMUHeatmapTileLayer.h
- src/Heatmap/GMUHeatmapTileLayer.m
- src/Heatmap/GMUWeightedLatLng.h
- src/Heatmap/GMUWeightedLatLng.m
- workspace/GoogleMapsUtils.xcodeproj/project.pbxproj
This is mostly a port of the Android version.  But there are some significant changes to color mapping in an attempt to avoid the mapping being dependent on the size of the data's bounding box.
> Update with initial heat maps implementation.

- Google-Maps-iOS-Utils.podspec
Getting ready for public release.
> Update Google-Maps-iOS-Utils.podspec to 2.1.0

- samples/ObjCDemoApp/ObjCDemoApp.xcodeproj/project.pbxproj
- samples/ObjCDemoApp/Podfile
- samples/SwiftDemoApp/Podfile
- samples/SwiftDemoApp/SwiftDemoApp.xcodeproj/project.pbxproj
- workspace/GoogleMapsUtils.xcodeproj/project.pbxproj
- workspace/Podfile
> Adding platform and path to the sample pod files.

- src/Heatmap/GMUHeatmapTileLayer.h
- src/Heatmap/GMUHeatmapTileLayer.m
This small PR is based on #143 , adding customizable zoom intensities to the heat-map.
> Make heat-map zoom intensities customizable

- samples/ObjCDemoApp/ObjCDemoApp.xcodeproj/project.pbxproj
- samples/ObjCDemoApp/ObjCDemoApp/Assets.xcassets/AppIcon.appiconset/Contents.json
- samples/ObjCDemoApp/ObjCDemoApp/ViewController.m
Fixes crash in sample due to an incorrect method signature.
> fix: Crash when tapping on cluster. Fixes #250.

- CHANGELOG.md
- Google-Maps-iOS-Utils.podspec
- README.md
- workspace/GoogleMapsUtils.xcodeproj/project.pbxproj
> chore(Release): v3.0.2

- .travis.yml
Deploy to CocoaPods on a new tag.
> build: pod trunk push on a tag.

- app/Resources/KML/KML_Sample.kml
- samples/SwiftDemoApp/SwiftDemoApp/KMLViewController.swift
- src/Geometry/GMUGeometryRenderer.m
- src/Geometry/GMUKMLParser.m
- test/resources/KML/KML_StyleMap_Test.kml
- test/unit/Geometry/GMUKMLParserTest.m
- workspace/GoogleMapsUtils.xcodeproj/project.pbxproj
Parsing `StyleMap` properly node in KML.
Fixes #285
> fix: Parse StyleMap in KML

- src/Clustering/Algo/GMUNonHierarchicalDistanceBasedAlgorithm.h
- src/Clustering/Algo/GMUNonHierarchicalDistanceBasedAlgorithm.m
Creating another initializer for GMUNonHierarchicalDistanceBasedAlgorithm to allow customizing the cluster distance.
Fixes #289 🦕
> feat: Allowing cluster distance customization

- Cartfile
- Cartfile.resolved
Use official Carthage binary distribution for Maps SDK.
> chore: Update Cartfile

- samples/SwiftDemoApp/SwiftDemoApp.xcodeproj/project.pbxproj
- samples/SwiftDemoApp/SwiftDemoApp/MasterViewController.swift
- samples/SwiftDemoApp/SwiftDemoApp/Samples.swift
Update `SwiftDemoApp` to use Swift 5.0 and above. 
Change Some Data Type in Samples classes to more understandable for developers have no experience with `Objc-c` Data Types.
> chore: Update Swift demo to use Swift 5.0

- CONTRIBUTORS.txt
- samples/SwiftDemoApp/SwiftDemoApp.xcodeproj/project.pbxproj
- samples/SwiftDemoApp/SwiftDemoApp/MasterViewController.swift
- samples/SwiftDemoApp/SwiftDemoApp/Sample.swift
- samples/SwiftDemoApp/SwiftDemoApp/Samples.swift
---
Fixes #<issue_number_goes_here> 🦕
> refactor: More improvisations in the Demo Applications.

- GoogleMapsUtils.xcodeproj/project.pbxproj
- src/Heatmap/GMUHeatmapTileLayer+Testing.h
- test/unit/Heatmap/GMUHeatmapTileLayerTest.swift
---
Fixes #<issue_number_goes_here> 🦕
> test: Code Coverage Increased from 67% to 74%

- GoogleMapsUtils.xcodeproj/project.pbxproj
- src/Clustering/View/GMUDefaultClusterRenderer+Testing.h
- src/Clustering/View/GMUDefaultClusterRenderer.h
- src/Geometry/GMUGeometryRenderer+Testing.h
- test/unit/BridgingHeader/UnitTest-Bridging-Header.h
- test/unit/Clustering/GMUDefaultClusterIconGeneratorTest.m
- test/unit/Clustering/GMUDefaultClusterRendererTest.m
- test/unit/Clustering/GMUSimpleClusterAlgorithmTest.swift
- test/unit/Geometry/GMUGeometryRendererTest.m
- test/unit/Heatmap/GMUHeatmapTileLayerTest.swift
---
Fixes #<issue_number_goes_here> 🦕
> test: Code Coverage increased to 85.4%

- .github/workflows/release.yml
- .releaserc
- Package.swift
- README.md
Adding support for Swift Package Manager.
-----
Fixes #305 #292 🦕
> feat: Support Swift Package Manager.

- .github/workflows/build.yml
Add GitHub workflow so that app apps are built and part of PR checks.
> build: Add workflow to build DevApp, SwiftDemoApp, ObjCDemoApp.

- CONTRIBUTING.md
Updating contributing instructions to include carthage instructions and also describe all supported schemes.
> docs: Update CONTRIBUTING.md with instructions to installing dependencies.

- HeatmapRendering.md
I added a short description to HeatmapRendering.md with an image of a sample heat map result. The markers (4) indicate the four data points given. Every other point in the heat map was artificially created.
> docs: Added description of heat map interpolation into HeatmapRendering.md

- Cartfile.resolved
> chore: Update GoogleMaps to 4.0.0

- .releaserc
- GoogleMapsUtils.xcodeproj/project.pbxproj
- Podfile.template
- samples/ObjCDemoApp/ObjCDemoApp.xcodeproj/project.pbxproj
- samples/ObjCDemoApp/Podfile
- samples/SwiftDemoApp/Podfile
- samples/SwiftDemoApp/SwiftDemoApp.xcodeproj/project.pbxproj
* Creating template for `Podfile`
* Bumping sample deployment target to 10.0
* Specifying version 4.0.0 for GoogleMaps dependency
> chore: Adding Podfile.template and bumping sample versions to 4.0.0 requirements.

- Cartfile.resolved
Bump the version number to 4.1.0.
> chore: Update cartfile.resolved for iOS 4.1.0

- Cartfile.resolved
- GoogleMapsUtils.xcodeproj/project.pbxproj
- src/GeometryUtils/CLLocationCoordinate2D+GeometryUtils.swift
- src/GeometryUtils/Internal/LatLngRadians.swift
- src/GeometryUtils/Math.swift
- test/unit/GeometryUtils/CLLocationCoordinate2D+GeometryUtilsTest.swift
- test/unit/GeometryUtils/GMSPath+GeometryUtilsTest.swift
- test/unit/GeometryUtils/Internal/LatLngRadiansTest.swift
> feat: Create extension for GMSGeometryHeading, GMSGeometryInterpolate, and GMSGeometryOffset on CLLocationCoordinate2D

- src/GeometryUtils/GMSPath+GeometryUtils.swift
- src/GeometryUtils/GMSPolyline+GeometryUtils.swift
- src/GeometryUtils/Math.swift
> feat: Swift extensions for GMSStyleSpans and GMSStyleSpansOffset on GMSPath

- .github/workflows/test.yml
- Google-Maps-iOS-Utils.podspec
- samples/SwiftDemoApp/Podfile
- src/GeometryUtils/Math.swift
- test/common/Model/GMUTestClusterItem.h
- test/unit/Clustering/GMUDefaultClusterRendererTest.m
- test/unit/Geometry/GMUGeoJSONParserTest.m
- test/unit/Geometry/GMUGeometryRendererTest.m
- test/unit/Geometry/GMUKMLParserTest.m
Add unit test subspec and `GeometryUtils` subspec.
> feat: Add unit test subspec and GeometryUtils subspec.

- samples/SwiftDemoApp/SwiftDemoApp/GeoJSONViewController.swift
- samples/SwiftDemoApp/SwiftDemoApp/KMLViewController.swift
- src/Heatmap/HeatMapInterpolationPoints.swift
`data.count > 0` is costly operation compared to `!data.isEmpty.` 
Safely unwrapped `path` in sample app
> chore: Changed count > 0 to isEmpty check

- .github/workflows/release.yml
- GoogleMapsUtils.xcodeproj/project.pbxproj
Possible fix for #347
Fixes #347 🦕
> fix: Set SKIP_INSTALL = NO

- .github/workflows/test.yml
- Cartfile
- Cartfile.resolved
- GoogleMapsUtils.xcodeproj/project.pbxproj
- README.md
Support XCFramework Carthage installation. Relates to #391
> feat: Depend on 6.0.1-beta for Carthage installation.

- Cartfile
- Cartfile.resolved
- Podfile.template
> chore: update GoogleMaps dependency to v6.2.1

- .github/workflows/dependabot.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- Enable workflow call in test.yml for PR #438 to work
- Workaround in release.yml
> chore: fix workflows

- .releaserc
- README.md
Undo replacement of version numbers related to Carthage from commit d0a299c
> docs: revert unintentionally updated version numbers in Carthage docs

- Sources/GoogleMapsUtils/Geometry/GeoJSONParser/GMUGeoJSONParser1.swift
- Sources/GoogleMapsUtils/Geometry/GeoJSONParser/GMUGeoJSONParserConstants.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUFeature1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUGeometryCollection1.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/Geometry/GMUGeoJSONParserTest.swift
Refactored files, Adding Obj-C files for reference:
1. [GMUGeoJSONParser.h](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUGeoJSONParser.h)
2. [GMUGeoJSONParser.m](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUGeoJSONParser.m)
1. Refactor & Modernised `GMUGeoJSONParser` class
2. Fix properties variable type in `GMUFeature1` struct
3. Added reference to the newly created struct into `GMUGeoJSONParserTest` (Unit test)
1. All the tests of `GMUGeoJSONParserTest` are passing.
> refactor: Translate & Modernised `GMUGeoJSONParser` class of `Geometry` module.

- Sources/GoogleMapsUtils/QuadTree/Models/GQTBounds1.swift
- Sources/GoogleMapsUtils/QuadTree/Models/GQTPoint1.swift
- Sources/GoogleMapsUtils/QuadTree/PointQuadTree/GQTPointQuadTree1.swift
- Sources/GoogleMapsUtils/QuadTree/PointQuadTreeChild/GQTPointQuadTreeChild+Helper.swift
- Sources/GoogleMapsUtils/QuadTree/PointQuadTreeChild/GQTPointQuadTreeChild.swift
- Sources/GoogleMapsUtils/QuadTree/Protocols/GQTPointQuadTreeItem.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/QuadTree/GQTPointQuadTreeItemMock.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/QuadTree/GQTPointQuadTreeTest.swift
Refactored files, Adding Obj-C uni tests file for reference:
1. [GQTBounds](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GQTBounds.h)
2. [GQTPoint](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GQTPoint.h)
3. [GQTPointQuadTreeItem](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GQTPointQuadTreeItem.h)
4. [GQTPointQuadTree](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GQTPointQuadTree.m)
5. [GQTPointQuadTreeChild](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GQTPointQuadTreeChild.m)
6. …
> refactor: Translate & Modernised `QuadTree` module.

- Sources/GoogleMapsUtils/Geometry/KMLParser/GMUKMLParser1+Delegates.swift
- Sources/GoogleMapsUtils/Geometry/KMLParser/GMUKMLParser1.swift
- Sources/GoogleMapsUtils/Geometry/KMLParser/GMUKMLParserConstants.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/Geometry/GMUKMLParserTest.swift
1. Refactor & Modernised `GMUKMLParser` class.
2. Modified `GMUKMLParserTest` unit test.
Refactored & Modified files, Adding Obj-C file for reference:
1. [GMUKMLParser](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUKMLParser.m)
2. [GMUKMLParserTest](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Tests/GoogleMapsUtilsSwiftTests/unit/Geometry/GMUKMLParserTest.swift)
1. All the tests of `GMUKMLParser` are passing.
> refactor: Translate & Modernised `GMUKMLParser` class of `Geometry` module.

- Sources/GoogleMapsUtils/Clustering/Algorithms/Protocol/GMUClusterAlgorithm1.swift
- Sources/GoogleMapsUtils/Clustering/Protocols/GMUCluster1.swift
- Sources/GoogleMapsUtils/Clustering/Protocols/GMUClusterItem1.swift
1. Translate & Modernised `GMUClusterAlgorithm`
1. [GMUClusterAlgorithm](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUClusterAlgorithm.h)
> refactor: Translate & Modernised `GMUClusterAlgorithm` protocol of `Clustering` module.

- Sources/GoogleMapsUtils/Clustering/Algorithms/GridBasedCluster/GMUGridBasedClusterAlgorithm1.swift
- Tests/GoogleMapsUtilsSwiftTests/Common/Model/GMUTestClusterItem1.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/Clustering/GMUStaticClusterTest.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/Clustering/Mocks/MockGMUClusterItem.swift
1. Translate & Modernised `GMUGridBasedClusterAlgorithm`
2. Translate & Modernise `GMUTestClusterItem`, common model for Testing.
3. Translate & Modernise `GMUStaticClusterTest`, Unit Test.
1. [GMUGridBasedClusterAlgorithm](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUGridBasedClusterAlgorithm.m)
2. [GMUTestClusterItem](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Tests/GoogleMapsUtilsTestsHelper/include/GMUTestClusterItem.m)
3. [GMUStaticClusterTest](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Tests/GoogleMapsUtilsObjCTests/unit/GMUStaticClusterTest.m)
- Source File - `GMUNonHierarchicalDistanceBasedAlgorithm`
- Test File - …
> refactor: Translate & Modernise `GMUGridBasedClusterAlgorithm`, `GMUStaticClusterTest`(UT) & `GMUTestClusterItem`(Test) class of `Clustering` module.

- Sources/GoogleMapsUtils/QuadTree/Models/GQTBounds1.swift
- Sources/GoogleMapsUtils/QuadTree/Models/GQTPoint1.swift
- Sources/GoogleMapsUtils/QuadTree/PointQuadTree/GQTPointQuadTree1.swift
- Sources/GoogleMapsUtils/QuadTree/PointQuadTreeChild/GQTPointQuadTreeChild+Helper.swift
- Sources/GoogleMapsUtils/QuadTree/PointQuadTreeChild/GQTPointQuadTreeChild.swift
- Sources/GoogleMapsUtils/QuadTree/Protocols/GQTPointQuadTreeItem.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/QuadTree/GQTPointQuadTreeItemMock.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/QuadTree/GQTPointQuadTreeTest.swift
- Merge `QuadTree` module into `Cluster` module.
- As, `Cluster`[`GMUClusterItemQuadItem`] has dependency to `QuadTree` module[`GQTPointQuadTreeItem`].
> refactor: Merge `QuadTree` module into `Cluster` module.

- Sources/GoogleMapsUtils/Clustering/View/Protocols/GMUClusterIconGenerator1.swift
- Sources/GoogleMapsUtils/Clustering/View/Protocols/GMUClusterRenderer1.swift
1. Translate & Modernised `GMUClusterIconGenerator`, `GMUClusterRenderer` protocols.
1. [GMUClusterIconGenerator](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUClusterIconGenerator.h)
2. [GMUClusterRenderer](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUClusterRenderer.h)
> refactor: Translate & Modernise protocols for `Clustering` view module.

- Sources/GoogleMapsUtils/Clustering/View/DefaultRenderer/GMUClusterRendererDelegate1.swift
- Sources/GoogleMapsUtils/Clustering/View/DefaultRenderer/GMUDefaultClusterRenderer1.swift
- Sources/GoogleMapsUtils/Clustering/View/IconGenerator/GMUDefaultClusterIconGenerator1.swift
- Sources/GoogleMapsUtils/Clustering/View/IconGenerator/GMUDefaultClusterIconGeneratorError.swift
- Sources/GoogleMapsUtils/Clustering/View/IconGenerator/UIColor+Extension.swift
- Sources/GoogleMapsUtils/Clustering/View/Protocols/GMUClusterIconGenerator1.swift
- Sources/GoogleMapsUtils/Clustering/View/Protocols/GMUClusterRenderer1.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/Clustering/GMUDefaultClusterIconGeneratorTest.swift
1. Translate & Modernised `GMUDefaultClusterIconGenerator`, `GMUDefaultClusterRenderer` class.
2. Translate & Modernised `GMUDefaultClusterIconGeneratorTest ` Test class.
1. [GMUDefaultClusterIconGenerator](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUDefaultClusterIconGenerator.m)
2. [GMUDefaultClusterRenderer](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUDefaultClusterRenderer.m)
3. [GMUDefaultClusterIconGeneratorTest](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Tests/GoogleMapsUtilsObjCTests/unit/GMUDefaultClusterIconGeneratorTest.m)
> refactor: Translate & Modernise for `Clustering` view & test module. 

- Sources/GoogleMapsUtils/Heatmap/Gradient/GMUGradient1.swift
- Sources/GoogleMapsUtils/Heatmap/WeightedLatLng/GMUWeightedLatLng1.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/Heatmap/GMUWeightedLatLngTest.swift
1. Translate & Modernised `GMUGradient` class
2. Refactor `GMUGradientTest` test class. (Indentation & Obj-C Exception)
1. [GMUGradient](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUGradient.m)
2. [GMUGradientTest](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Tests/GoogleMapsUtilsSwiftTests/unit/Heatmap/GMUGradientTest.swift)
> refactor: Translate & Modernise `GMUGradient` class for `Heatmap` module.

- README.md
- Adding patch to [release-please--branches--main](https://github.com/googlemaps/google-maps-ios-utils/tree/release-please--branches--main) to update readme.md [file](https://github.com/googlemaps/google-maps-ios-utils/blob/main/README.md).
> chore(release-please--branches--main): Patch to release branch 6.1.0

- Sources/GoogleMapsUtils/Geometry/GeoJSONParser/GMUGeoJSONParser1.swift
- Sources/GoogleMapsUtils/Geometry/GeoJSONParser/GMUGeoJSONParserConstants.swift
- Sources/GoogleMapsUtils/Geometry/GeometryRenderer/GMUGeometryRenderer1.swift
- Sources/GoogleMapsUtils/Geometry/KMLParser/GMUKMLParser1+Delegates.swift
- Sources/GoogleMapsUtils/Geometry/KMLParser/GMUKMLParser1.swift
- Sources/GoogleMapsUtils/Geometry/KMLParser/GMUKMLParserConstants.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUFeature1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUGeometryCollection1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUGroundOverlay1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMULineString1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUPair1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUPlacemark1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUPoint1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUPolygon1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUStyle1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUStyleMap1.swift
- Sources/GoogleMapsUtils/Geometry/Protocols/GMUGeometry1.swift
- Sources/GoogleMapsUtils/Geometry/Protocols/GMUGeometryContainer1.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/Geometry/GMUGeoJSONParserTest.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/Geometry/GMUKMLParserTest.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/Geometry/Models/GMUGroundOverlayTest.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/Geometry/Models/GMULineStringTest.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/Geometry/Models/GMUPointTest.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/Geometry/Models/GMUPolygonTest.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/Geometry/Models/GMUStyleTest.swift
1. Merge `feature/Geometry-Swift` into `feature/Cluster-QuadTree-Heatmap-Geometry-swift` branch.
1. I did run the test suite post merge, it's passing.
> feat: Merge `feature/Geometry-Swift` into `feature/Cluster-QuadTree-Heatmap-Geometry-swift` branch.

- GoogleMapsUtils.xcodeproj/project.pbxproj
- GoogleMapsUtils.xcodeproj/xcshareddata/xcschemes/GoogleMapsUtils.xcscheme
- GoogleMapsUtils.xcodeproj/xcshareddata/xcschemes/GoogleMapsUtilsTests.xcscheme
- Sources/GoogleMapsUtils/Clustering/Algorithms/SimpleCluster/GMUSimpleClusterAlgorithm.swift
- Tests/GoogleMapsUtilsTests/unit/Clustering/GMUSimpleClusterAlgorithmTest.swift
- Add test for `GMUSimpleClusterAlgorithm` class from Clustering test module. 
- Code coverage: 100%
- Add Test Schemes
- Logic correction for `clusters(atZoom zoom: Float)` method, added this check `if clusterItems.count > clusterCount {`
- Tests are passing
> chore: Add test for `GMUSimpleClusterAlgorithm` class from Clustering test module. [code cov: 100%] 

- Package.resolved
- Package.swift
- README.md
- samples/ObjCDemoApp/ObjCDemoApp.xcodeproj/project.pbxproj
- samples/ObjCDemoApp/ObjCDemoApp/AppDelegate.m
- samples/ObjCDemoApp/Podfile
- samples/SwiftDemoApp/Podfile
- samples/SwiftDemoApp/SwiftDemoApp.xcodeproj/project.pbxproj
- samples/SwiftDemoApp/SwiftDemoApp/AppDelegate.swift
- Update Google Maps version[9.4.0] in Sample app & framework
- Update minimum iOS deployment version[15.0] in Sample app
- Add `addInternalUsageAttributionID` in the Sample app for AppDelegate.m & AppDelegate.swift files.
> chore: Update Google Maps version, minimum iOS deployment version, & attributionID addition
