googlemaps/google-maps-ios-utils

- CONTRIBUTORS.txt
- src/Clustering/View/GMUDefaultClusterIconGenerator.m
Improved pixel clarity of text and custom base images for clusters on Retina and Retina+ screens.
Before:
After:
> Retina screen support for custom icon images.

- src/Clustering/View/GMUDefaultClusterRenderer.h
- src/Clustering/View/GMUDefaultClusterRenderer.m
Allow GMUDefaultClusterRenderer to utilize the zIndex property for clusters.
This proves to be useful when using multiple GMUClusterManagers in a single map and allows a predictable drawing priority per cluster manager.
Example:
The blue clusters have a higher zIndex precedence than the grey cluster icon.  The 'blue' clusters are drawn on top regardless of zoom, pan or scroll.
> Allow GMUDefaultClusterRenderer to utilize the zIndex property for clusters.

- src/Clustering/GMUClusterManager+Testing.h
- src/Clustering/GMUClusterManager.h
- src/Clustering/GMUClusterManager.m
- src/Clustering/GMUMarkerClustering.h
- src/Clustering/GMUStaticCluster.h
- src/Clustering/GMUStaticCluster.m
Hey guys,
first of all, great utility library, love it! I use it to support clustering with Titanium and it works as expected. While fixing some recent Analyser warnings in my project, I noticed that the library also had one (trivial) warning. We use the following to disable the default initializer:
```objc
- (instancetype)init {
self = [self initWithNullableMap:nil algorithm:nil renderer:nil];
if (self) {
[self doesNotRecognizeSelector:_cmd];
self = nil;
}
return self;
}
```
The `initWithNullableMap:algorithm:renderer` method then assigns `nil` values to the properties and throws the `Unrecognized Selector` system error. But the `algorithm` property is non-null in the interface, so it throws the warning. Simple as that. The other ones are already `nullable`, so they pass the Analyser. …
> Fix Xcode Analyser warning by removing nullable (default) initializer

- src/Clustering/GMUMarkerClustering.h
Bug #104 - Fixed missing header entry for GMUStaticCluster protocol, enabling access by callers.
> Bug fix (#104) - GMUStaticCluster missing from library header

- src/Clustering/View/GMUDefaultClusterRenderer.h
This changes the return value to be an optional for swift, and allows
to use the default marker if returning nil from the swift delegate.
> Mark renderer:markerForObject: as nullable

- src/Clustering/GMUClusterManager.m
The method mapView:didTapPOIWithPlaceID:name:location: was missing, so
any app using a cluster manager was not able to react to taps on points
of interest.
> Implement mapView:didTapPOIWithPlaceID:name:location:

- src/Clustering/View/GMUDefaultClusterIconGenerator.m
Use kGMUBucketBackgroundColors to store the default colors, but don't reassign this during instance initialization. Instead, use an instance member to store the instance-specific background colours.
This fixes a bug where all Icon Generator instances would use the same background colours, regardless of what colours were passed in during construction.
> Fix for wrong icons when using multiple Cluster Managers (#158)

- src/Clustering/View/GMUDefaultClusterIconGenerator.m
/src/Clustering/View/GMUDefaultClusterIconGenerator.m
The _backgroundColors property should be of type NSArray<UIColor *>.
> backgroundColors fix

- src/Clustering/View/GMUDefaultClusterRenderer.m
This is a fix for issue #150 problem with animatesClusters. If a cluster was partially on the screen, the cluster's representative cluster item was off the screen, and the cluster was not to be rendered as a cluster, then the cluster would not be shown. Usually what I'd see is I'd change the zoom level and suddenly a cluster item (usually near the side of the screen) would disappear.
The fix is: when iterating through a cluster's items, if the cluster is not to be rendered as a cluster and if at least one cluster item is visible, then show the cluster. Otherwise the cluster item(s) will disppear from the screen.
As in @theolof's write up of the issue, setting animateClusters to `true` prevents this behavior because it forces each cluster to always be rendered.
> If cluster is expanded and an item is visible, show cluster

- src/Clustering/View/GMUDefaultClusterRenderer.m
Fix for issue #131 missing animation when kGMSMaxClusterSize is reached. Currently, when zooming in, if a cluster is not to be rendered as a cluster at the target zoom level then the cluster item animation is skipped. This is done irrespective of the previous zoom level. So if you double tap to zoom from level 12.5 to 13.5, and you have kGMSMaxClusterSize set at 13, then any visible clusters will dissolve without animation.
The fix I've implemented delays setting _previousZoom until after prepareClustersForAnimation:isZoomingIn: completes. And then to use _previousZoom in that method to detect whether a cluster is dissolving when zooming in in order to animate the placement of its cluster items.
> Fix no animation when kGMSMaxClusterZoom is reached

- src/Heatmap/GMUGradient.h
Typo in import (UIKIt instead of UIKit) led to failure when building on case sensitive file system
> Fix typo in Heatmap/GMUGradient.h import of UIKit header

- src/Geometry/GMUGeometryRenderer.h
- src/Geometry/GMUGeometryRenderer.m
- src/Geometry/GMUKMLParser.h
- src/Geometry/GMUKMLParser.m
- src/Geometry/Model/GMUPair.h
- src/Geometry/Model/GMUPair.m
- src/Geometry/Model/GMUStyleMap.h
- src/Geometry/Model/GMUStyleMap.m
https://developers.google.com/kml/documentation/kmlreference#stylemap
I am using this lib on both Android and iOS versions of my app.
The KML file that I am using contains StyleMap tags. On Android it renders well, but on iOS the Placemarks have no colors.
I've noticed that the KML Parser in the iOS lib has support for fewer tags than the one for Android, so I had to add this one myself. Maybe this will be useful for others as well..
> Adds support for StyleMap

- workspace/GoogleMapsUtils.xcodeproj/project.pbxproj
The `GMUPair.h/m` and `GMUStyleMap.h/m` files were not included in the Xcode project, which was causing build issues when attempting to compile the framework, unit tests, or dev app.
> Fix Build Issues Caused by GMUPair and GMUStyleMap

- app/BasicViewController.m
- src/Clustering/View/GMUDefaultClusterRenderer.h
- src/Clustering/View/GMUDefaultClusterRenderer.m
- src/Geometry/GMUGeometryRenderer.m
- test/unit/Clustering/GMUClusterAlgorithmTest.h
- test/unit/Clustering/GMUClusterManagerTest.m
- test/unit/Clustering/GMUDefaultClusterRendererTest.m
- test/unit/Geometry/GMUGeometryRendererTest.m
- workspace/GoogleMapsUtils.xcodeproj/project.pbxproj
Hey there,
this pull refactors a few Xcode 10 warnings as well as exposes the (currently private) renderer configuration properties that help the developer to fine-tune the cluster experience based on the use case. Finally, this pull fixes one unit tests and three unit test warnings. All tests still pass with this change and the change is 100 % backward compatible.
> feat: expose private cluster configuration to public API, resolve Xcode 10 warnings

- src/Clustering/GMUClusterManager.m
This PR fixes https://github.com/googlemaps/google-maps-ios-utils/issues/215.  The `GMSClusterManager` class previously only maintained a weak reference to its `GMSMapView` instance variable.  This could cause potential crashes if the `GMSMapView` object ever deallocated before the `removeObserver:forKeyPath:` method could be called from `dealloc`.
Per [Apple documentation](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/KeyValueObserving/Articles/KVOBasics.html), strong references should be maintained for objects observed via KVO:
> Note: The key-value observing addObserver:forKeyPath:options:context: method does not maintain strong references to the observing object, the observed objects, or the context. You should ensure that you maintain strong references to …
> Maintain strong reference to GMSMapView in GMSClusterManager

- CONTRIBUTORS.txt
- src/Geometry/GMUGeometryRenderer.m
Fixes #209: GMUGeometryRenderer is not applying the external styles when no styleMaps are specified
> Fixes #209: GMUGeometryRenderer is not applying the external styles when no styleMaps are specified

- samples/SwiftDemoApp/SwiftDemoApp.xcodeproj/project.pbxproj
- samples/SwiftDemoApp/SwiftDemoApp/AppDelegate.swift
- samples/SwiftDemoApp/SwiftDemoApp/HeatmapViewController.swift
Updating the Swift demo to use Swift 4.2. The demo with Swift 3 was unusable in the latest version of Xcode.
> feat: Update Swift demo to use Swift 4.2

- samples/ObjCDemoApp/Podfile
- samples/SwiftDemoApp/Podfile
- workspace/Podfile
Speeding up initial `pod install` by using CDN instead of the CocoaPods master repo (i.e. if you don't have a `~/.cocoapods` directory yet and one needs to be initialized). See the [CocoaPods blog post](http://blog.cocoapods.org/CocoaPods-1.7.2/) for more info. I noticed a 50% speed up.
**Benchmark on Macbook Pro 2.6 GHz Intel Core i7**
| Method      | Time (in secs) |
| ------------- | ------------- |
| Master Repo  | 343  |
| CDN  |  162  |
> build(CocoaPods): speed up initial pod install by using CDN.

- workspace/GoogleMapsUtils.xcodeproj/xcshareddata/xcschemes/UnitTest.xcscheme
- workspace/GoogleMapsUtils/GoogleMapsUtils.h
Disabled broken unit tests to allow CI to pass again. Also removed `GoogleMaps.h` from `GoogleMapsUtils.h` header file—that shouldn't have been there.
Relates to #267
> test: Disable broken unit tests

- Google-Maps-iOS-Utils.podspec
Remove specific dependency to GoogleMaps version 3.7.0. A regression introduced in a33e821f.
Fixes #275 🦕
> feat: Remove version from podspec dependency.

- samples/ObjCDemoApp/Podfile
- samples/SwiftDemoApp/Podfile
- workspace/Podfile
Using CocoaPods CDN speeds up initialization of CocoaPods so that the master repo
doesn't need to be instantiated on first install. However, the CDN is a 1.8+ feature
and 1.8+ is not compatible with the pod try plugin (See: https://github.com/CocoaPods/cocoapods-try/issues/63).
As a workaround, reverting 4d9799d for now so that `pod try Google-Maps-iOS-Utils` works on CocoaPods versions < 1.8.
> fix: Revert 4d9799d so that the lib is compatible with pod try

- src/Clustering/View/GMUDefaultClusterRenderer.m
- test/common/Model/GMUTestClusterItem.h
- test/common/Model/GMUTestClusterItem.m
- test/unit/Clustering/GMUDefaultClusterRendererTest.m
Fixes crash in GMUClusterManager by inspecting if a conforming
GMUClusterItem responds to the selectors title and snippet before
accessing it.
Closes #300.
> fix: Fix crash in GMUClusterManager

- samples/SwiftDemoApp/SwiftDemoApp/ClusteringViewController.swift
- src/Clustering/GMUClusterItem.h
The `readonly` keyword on `GMUClusterItem` title and snippet were
making title and snippet on `GMSMarker` immutable. Removing this keyword
and marking properties as `copy` to match `GMSMarker` fixes this.
Fixes #300
> fix: Make title and snippet mutable for GMUClusterItem.

- samples/SwiftDemoApp/SwiftDemoApp/MasterViewController.swift
1. Moved `cellIdentifier` to variable declaration section.
2. Removed the unnecessary force unwrapping[!] for UITableViewCell.
---
Fixes #<issue_number_goes_here> 🦕
> refactor: Removing the unnecessary force unwrapping[!] for UITableViewCell

- .github/workflows/release.yml
> fix: Adding missing -r flag when zipping .xcframework

- src/Clustering/View/GMUDefaultClusterRenderer.m
Fixes issue when zooming in on an unclustered marker. This was primarily an issue if you added a `GMSMarker` directly into the `GMUClusterManager` - it was not an issue for other objects conforming to `GMUClusterItem`.
Fixes #321 🦕
> fix(Clustering): Disappearing marker when zooming in.

- GoogleMapsUtils.xcodeproj/project.pbxproj
- src/GeometryUtils/MapPoint.swift
- test/unit/GeometryUtils/MapPointTest.swift
Adding `MapPoint.swift` which provides alternative Swift-friendly APIs to functions within the Maps SDK [GMSGeometryUtils](https://developers.google.com/maps/documentation/ios-sdk/reference/group___geometry_utils) module.
* `MapPoint` can be used in place of `GMSMapPoint`
* The extension property on `CLLocationCoordinate2D`, `mapPoint`, can be used in place of `GMSProject`
* The property on `MapPoint`, `location`, can be used in place of `GMSUnproject`
* The static function on `MapPoint`, `interpolate(from:, to:, fraction:)` can be used in place of `GMSMapPointInterpolate`
* The function on `MapPoint`, `distance(to: )`, can be used in place of `GMSMapPointDistance`
> feat: Adding MapPoint.

- .github/workflows/release.yml
The new default branch is `main`, not `master`. Update the Xcode version to 12.2.
> chore: Run release.yml on main.

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- Google-Maps-iOS-Utils.podspec
- carthage.sh
- src/Clustering/View/GMUDefaultClusterRenderer.m
When clustering/declustering, the `userData` property of a marker can be nil'd. This is due to markers being removed from the map when the zoom level changes.
For example, when the zoom level changes and the marker representing a cluster should no longer be displayed, this marker is cleared. However, markers that don't
represent clusters were incorrectly cleared but this only happens if you add a `GMSMarker` directly to the `GMUClusterManager` and not if you are using another 
class conforming to `GMUClusterItem`. The fix here is to only clear the `userData` field if the marker being cleared represents a cluster.
Fixes #349 🦕
> fix: nil userData on marker when clustering/declustering.

- src/Geometry/GMUGeometryRenderer.m
Fixes #375 🦕
I have tried and tested the tappable geometry rendered.
> feat: add overlay tappable for geometry renderder

- Google-Maps-iOS-Utils.podspec
- samples/ObjCDemoApp/ObjCDemoApp.xcodeproj/project.pbxproj
- samples/ObjCDemoApp/Podfile
- samples/SwiftDemoApp/Podfile
- samples/SwiftDemoApp/SwiftDemoApp.xcodeproj/project.pbxproj
- samples/SwiftDemoApp/SwiftDemoApp/GeoJSONViewController.swift
Fixes #391
Google Maps 7.3.0's CocoaPods version now [uses XCFramework](https://developers.google.com/maps/documentation/ios-sdk/release-notes), so Google-Maps-iOS-Utils should not use `EXCLUDED_ARCHS` anymore.
> feat: Support Simulator on ARM Macs

- .github/workflows/release.yml
Workaround specifying Node 14 requires specifying older versions of semantic-release based on Node 14.
> chore: semantic release dependencies

- README.md
Generate release after release workflow dependency fix in #443 
Fixes #445
> fix: re-release with XCFramework and improve README

- .github/workflows/build.yml
- .releaserc
Add asset to semantic-release-replace-plugin release config and trigger new patch release after updating token.
> fix: release config

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
Update workflows to use minimums for 8.0.0 in preparation for major version bump.
Fixes #433 🦕
> chore: update workflows

- .github/workflows/build.yml
- .github/workflows/release-please.yml
- Google-Maps-iOS-Utils.podspec
- README.md
- Run build and test on all pushes to main
- Try updating only the Google-Maps-iOS-Utils dependency line in README
- Fix trigger to call publish workflow
> chore: refine workflows

- .github/workflows/release-please.yml
- README.md
- release-please-config.json
1. The release worfklow is failing because the call to the publish workflow requires checkout first, which must not be handled under a separate conditional.
2. Release Please is unable to distinguish between version numbers of this package that should be bumped up with each release vs other strings that represent version numbers but shouldn't be bumped. This causes an extra manual commit on the release PR to correct the edits that release-please makes. Since the README has 3 strings that shouldn't be bumped and 1 instance that should be bumped, we will manually update the bump until Release Please can support a more detailed regex (feature request in https://github.com/googleapis/release-please/issues/2345)
> chore: fix release-to-publish workflow

- Sources/GoogleMapsUtils/Geometry/Models/GMULineString1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUPair1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUPlacemark1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUStyle1.swift
- Sources/GoogleMapsUtils/Geometry/Protocols/GMUGeometry1.swift
- Sources/GoogleMapsUtils/Geometry/Protocols/GMUGeometryContainer1.swift
List of Refactored Files, Adding Obj-C file for reference:
1. [GMULineString](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMULineString.h)
2. [GMUPair](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUPair.h)
3. [GMUPlacemark](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUPlacemark.h)
4. [GMUStyle](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUStyle.h)
5. [GMUGeometry](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUGeometry.h)
6. [GMUGeometryContainer](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/Goo …
> refactor(`feature/Geometry-Swift`): Refactored Geometry models & Protocols in swift.

- Sources/GoogleMapsUtils/Geometry/Models/GMUFeature1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUGeometryCollection1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUGroundOverlay1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUPoint1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUPolygon1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUStyle1.swift
- Sources/GoogleMapsUtils/Geometry/Models/GMUStyleMap1.swift
- Sources/GoogleMapsUtils/Geometry/Protocols/GMUGeometry1.swift
- Sources/GoogleMapsUtils/Geometry/Protocols/GMUGeometryContainer1.swift
List of Refactored Files, Adding Obj-C file for reference:
1. [GMUFeature](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUFeature.h)
2. [GMUGeometryCollection](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUGeometryCollection.h)
3. [GMUGroundOverlay](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUGroundOverlay.h)
4. [GMUPoint](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUPoint.h)
5. [GMUPolygon](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUPolygon.h)
6. [GMUStyleMap](https://github.com/googlemaps/google-maps-ios-utils/bl …
> refactor: Refactored `Geometry` models in swift & `optional`/`nullable` properties of the recently committed swift class.

- Sources/GoogleMapsUtils/Clustering/Protocols/GMUCluster1.swift
- Sources/GoogleMapsUtils/Clustering/Protocols/GMUClusterItem1.swift
1. Translate & Modernised `GMUCluster` & `GMUClusterItem`
1. [GMUCluster](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUCluster.h)
2. [GMUClusterItem](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUClusterItem.h)
> refactor: Translate & Modernised `GMUCluster` & `GMUClusterItem` class of `Clustering` module.

- Sources/GoogleMapsUtils/Clustering/Algorithms/WrappingDictionaryKey/GMUWrappingDictionaryKey1.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/Clustering/GMUWrappingDictionaryKeyTest.swift
1. Translate & Modernised `GMUWrappingDictionaryKey`
2. Translate & Modernise `GMUWrappingDictionaryKeyTest`, Unit Test.
1. [GMUWrappingDictionaryKey](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUWrappingDictionaryKey.m)
3. [GMUWrappingDictionaryKeyTest](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Tests/GoogleMapsUtilsObjCTests/unit/GMUWrappingDictionaryKeyTest.m)
> refactor: Translate & Modernise `GMUWrappingDictionaryKey` class, `GMUWrappingDictionaryKeyTest`(UT) of `Clustering` module.

- Sources/GoogleMapsUtils/Heatmap/WeightedLatLng/GMUWeightedLatLng1.swift
- Tests/GoogleMapsUtilsSwiftTests/unit/Heatmap/GMUWeightedLatLngTest.swift
1. Translate & Modernised `GMUWeightedLatLng`.
2. Refactored Test `GMUWeightedLatLngTest`
1. [GMUWeightedLatLng](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Sources/GoogleMapsUtilsObjC/include/GMUWeightedLatLng.m)
> refactor: Translate & Modernise `GMUWeightedLatLng` class for `HeatMap` module.

- Sources/GoogleMapsUtilsObjC/include/GMUDefaultClusterRenderer.m
When 
If can not subclass GMSMarker with custom iconView can not see iconView on Map
---
Fixes #505  🦕
> feat: Add GMSMarker subclass allowance on cluster renderer

- docs/GeometryUtils.md
The following PR fixes some broken URLs in the [GeometryUtils](https://github.com/googlemaps/google-maps-ios-utils/blob/main/docs/GeometryUtils.md) README file. Now the links are pointing out to the correct URL.
> chore: fixed broken URLs

- release-please-config.json
Formatting based on https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#configfile
Although this is a single-package repo, the configfile README indicates we should set most options at the top level of the JSON and only a couple of properties are set in the package-specific config.
> chore: update release-please-config.json

- GoogleMapsUtils.xcodeproj/project.pbxproj
- Tests/GoogleMapsUtilsTests/unit/Clustering/GMUClusterManagerTests.swift
- Tests/GoogleMapsUtilsTests/unit/Clustering/Mocks/MockCluster.swift
- Tests/GoogleMapsUtilsTests/unit/Clustering/Mocks/MockClusterAlgorithm.swift
- Tests/GoogleMapsUtilsTests/unit/Clustering/Mocks/MockClusterManagerDelegate.swift
- Tests/GoogleMapsUtilsTests/unit/Clustering/Mocks/MockClusterRenderer.swift
- Tests/GoogleMapsUtilsTests/unit/Clustering/Mocks/MockGMSMapView.swift
- Tests/GoogleMapsUtilsTests/unit/Clustering/Mocks/MockMapDelegate.swift
- Translate & Modernise `GMUClusterManagerTests` test class from Clustering test module.
- Code cov: 92.4%
- Source File: [GMUClusterManagerTest.m](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Tests/GoogleMapsUtilsObjCTests/unit/GMUClusterManagerTest.m)
> refactor: Translate & Modernise `GMUClusterManagerTests` test class from Clustering test module. [code cov: 92.4%]

- GoogleMapsUtils.xcodeproj/project.pbxproj
- Sources/GoogleMapsUtils/Clustering/View/DefaultRenderer/GMUDefaultClusterRenderer.swift
- Tests/GoogleMapsUtilsTests/unit/Clustering/GMUDefaultClusterRendererTest.swift
- Tests/GoogleMapsUtilsTests/unit/Clustering/Mocks/MockClusterIconGenerator.swift
- Tests/GoogleMapsUtilsTests/unit/Clustering/Mocks/MockGMSMapView.swift
- Tests/GoogleMapsUtilsTests/unit/Clustering/Mocks/MockGMSProjection.swift
- Translate & Modernise `GMUDefaultClusterRendererTest` test class from Clustering test module.
- Code cov: 78.3%
- Source File: [GMUDefaultClusterRendererTest.m](https://github.com/googlemaps/google-maps-ios-utils/blob/main/Tests/GoogleMapsUtilsObjCTests/unit/GMUDefaultClusterRendererTest.m)
> refactor: Translate & Modernise `GMUDefaultClusterRendererTest` test class from Clustering test module. [code cov: 78.3%]
